# Generated by Django 3.2.16 on 2022-11-08 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='CityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_created=True)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='REST_API.city')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_created=True)),
                ('validTill', models.DateTimeField(auto_created=True)),
                ('validFrom', models.DateTimeField(auto_created=True)),
                ('Code', models.CharField(max_length=90)),
                ('discount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=10)),
                ('perKilo', models.FloatField()),
                ('perMin', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_created=True, auto_now=True)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleRegistrationFile', models.FileField(upload_to='VehicleRegistrationFile')),
                ('vehicleImg', models.FileField(upload_to='VehicleImg')),
                ('color', models.CharField(max_length=10)),
                ('numberPlate', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('vehicleType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='REST_API.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_created=True)),
                ('rideImg', models.ImageField(upload_to='RideImg')),
                ('distance', models.FloatField(default=0.0)),
                ('pickUpTime', models.TimeField(null=True)),
                ('dropOffTime', models.TimeField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('fare', models.FloatField()),
                ('driverArrivalTime', models.TimeField(null=True)),
                ('isRideActive', models.BooleanField(default=True)),
                ('groupId', models.CharField(max_length=20)),
                ('coupon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='REST_API.coupon')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='REST_API.cityuser')),
                ('driverLocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='REST_API.currentlocation')),
                ('dropOffAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropOffAddress', to='REST_API.address')),
                ('pickUpAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickUpAddress', to='REST_API.address')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider', to='REST_API.cityuser')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_created=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('cnic', models.CharField(max_length=20)),
                ('driverLicenseNumber', models.CharField(max_length=20)),
                ('driverLicenseExpiry', models.DateField()),
                ('driverLicenseImg', models.ImageField(upload_to='DriverLicenseImg')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='REST_API.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='cityuser',
            name='driver_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='REST_API.driver'),
        ),
        migrations.AddField(
            model_name='cityuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cityuser',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='REST_API.wallet'),
        ),
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDriver', models.BooleanField()),
                ('message', models.TextField()),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST_API.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
