# Generated by Django 3.2.16 on 2022-11-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0002_alter_cityuser_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityuser',
            name='dp',
            field=models.ImageField(null=True, upload_to='userDP'),
        ),
    ]
