# Generated by Django 3.2.16 on 2022-11-11 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0003_cityuser_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST_API.vehicletype'),
        ),
    ]
