# Generated by Django 3.2.16 on 2022-11-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0004_alter_vehicle_vehicletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='isApproved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
