# Generated by Django 3.2.16 on 2022-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0005_alter_driver_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='creationDate',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
