# Generated by Django 3.2.16 on 2022-11-12 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0007_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='isOtpVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cityuser',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST_API.city'),
        ),
    ]
