# Generated by Django 3.2.16 on 2022-11-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0008_auto_20221112_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.TextField(max_length=4),
        ),
    ]
