# Generated by Django 3.2.16 on 2022-11-13 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0009_alter_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='isRideActive',
        ),
        migrations.AddField(
            model_name='ride',
            name='rideStatus',
            field=models.CharField(choices=[('CN_RI', 'CANCEL_BY_RIDER'), ('CN_DR', 'CANCEL_BY_DRIVER'), ('SR', 'SEARCHING'), ('IP', 'IN_PROGRESS'), ('CMP', 'COMPLETED')], default='SR', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='bookingFee',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='cancellationFee',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='minimumPrice',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='waitTime',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cityuser',
            name='driver_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REST_API.driver'),
        ),
        migrations.AlterField(
            model_name='cityuser',
            name='phoneNumber',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='ride',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REST_API.coupon'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='creationDate',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='REST_API.cityuser'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driverArrivalTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driverLocation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REST_API.currentlocation'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='dropOffAddress',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropOffAddress', to='REST_API.address'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='dropOffTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='fare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='PAV4OY9IO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickUpAddress',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickUpAddress', to='REST_API.address'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickUpTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='rideImg',
            field=models.ImageField(blank=True, null=True, upload_to='RideImg'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='rider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider', to='REST_API.cityuser'),
        ),
    ]
