# Generated by Django 3.2.16 on 2022-11-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0010_auto_20221114_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='image',
            field=models.ImageField(default=10, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='A0N2RYR2M', max_length=20),
        ),
    ]
