# Generated by Django 3.2.16 on 2022-11-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0011_auto_20221115_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='XJOY3PX01', max_length=20),
        ),
    ]
