# Generated by Django 3.2.16 on 2022-11-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0012_alter_ride_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='UT3NUDJV3', max_length=20),
        ),
    ]
