# Generated by Django 3.2.16 on 2022-11-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0014_auto_20221115_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='BM8QCXRG2', max_length=20),
        ),
    ]
