# Generated by Django 3.2.16 on 2022-11-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0015_alter_ride_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='13IM9083P', max_length=20),
        ),
    ]
