# Generated by Django 3.2.16 on 2022-11-15 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0016_auto_20221115_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='rating',
        ),
        migrations.AddField(
            model_name='cityuser',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='REST_API.cityuser'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='P239EJV38', max_length=20),
        ),
    ]
