# Generated by Django 3.2.16 on 2022-11-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0017_auto_20221115_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='F9FFKVYBD', max_length=20),
        ),
    ]
