# Generated by Django 3.2.16 on 2022-11-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0018_alter_ride_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='company',
            field=models.CharField(default='Toyota', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='LDBCMKI7R', max_length=20),
        ),
    ]
