# Generated by Django 3.2.16 on 2022-11-25 09:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0019_auto_20221117_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatting',
            name='dateTime',
        ),
        migrations.RemoveField(
            model_name='chatting',
            name='isDriver',
        ),
        migrations.AddField(
            model_name='chatting',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatting',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentlocation',
            name='heading',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='chatting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST_API.cityuser'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='6W1NNV8LT', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='rideStatus',
            field=models.CharField(choices=[('RD_ST', 'RIDE_STARTED'), ('DR_AR', 'DRIVER_ARRIVED'), ('CN_RI', 'CANCEL_BY_RIDER'), ('CN_DR', 'CANCEL_BY_DRIVER'), ('SR', 'SEARCHING'), ('IP', 'IN_PROGRESS'), ('CMP', 'COMPLETED')], default='SR', max_length=20),
        ),
    ]
