# Generated by Django 3.2.16 on 2022-11-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0020_auto_20221125_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='duration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='WZXN2I3NW', max_length=20),
        ),
    ]
