# Generated by Django 3.2.16 on 2022-11-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0021_auto_20221125_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='8667BRCRI', max_length=20),
        ),
    ]
