# Generated by Django 3.2.16 on 2022-11-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0022_auto_20221126_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='maxUses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REST_API.coupon'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='0BOGMI639', max_length=20),
        ),
    ]
