# Generated by Django 3.2.16 on 2022-11-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0023_auto_20221126_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='timesUsed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='EJ0GFJ4M0', max_length=20),
        ),
    ]
