# Generated by Django 3.2.16 on 2022-11-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0024_auto_20221126_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityuser',
            name='cityName',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='PO7ADVN0F', max_length=20),
        ),
    ]
