# Generated by Django 3.2.16 on 2022-11-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0025_auto_20221126_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityuser',
            name='city',
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='2SX0VXZZH', max_length=20),
        ),
    ]
