# Generated by Django 3.2.16 on 2022-11-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0026_auto_20221126_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='maxUses',
            new_name='NoOfRides',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='timesUsed',
        ),
        migrations.AddField(
            model_name='coupon',
            name='isActive',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='Code',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='validFrom',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='validTill',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='JFVHLJZ6Y', max_length=20),
        ),
    ]
