# Generated by Django 3.2.16 on 2022-11-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0027_auto_20221126_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='validFrom',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='validTill',
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='DJR6CSWF4', max_length=20),
        ),
    ]
