# Generated by Django 3.2.16 on 2022-11-26 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0028_auto_20221126_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='validFrom',
            field=models.DateField(auto_created=True, default=datetime.date(2022, 11, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='validTill',
            field=models.DateField(auto_created=True, default=datetime.date(2022, 11, 26)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='02UE1WQPL', max_length=20),
        ),
    ]
