# Generated by Django 3.2.16 on 2022-11-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0029_auto_20221126_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logType', models.CharField(choices=[('NC', 'New Client'), ('PC', 'PC'), ('DP', 'Dp Change'), ('OT', 'other')], default='OT', max_length=20)),
                ('log', models.TextField()),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='JS2UJGEWR', max_length=20),
        ),
    ]
