# Generated by Django 3.2.16 on 2022-11-27 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('REST_API', '0030_auto_20221127_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='authStatus',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='CO325R60I', max_length=20),
        ),
        migrations.CreateModel(
            name='CityAdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_created=True, auto_now=True)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('dp', models.ImageField(null=True, upload_to='userDP')),
                ('user', models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
