# Generated by Django 3.2.16 on 2022-11-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0031_auto_20221127_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityuser',
            name='notificationToken',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='IY8CWT184', max_length=20),
        ),
    ]
