# Generated by Django 3.2.16 on 2022-11-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0032_auto_20221127_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityadminuser',
            name='isNotification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='HBXEE48V3', max_length=20),
        ),
    ]
