# Generated by Django 3.2.16 on 2022-11-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0033_auto_20221127_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='preferredRideType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='REST_API.vehicletype'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='ANKDVMEFX', max_length=20),
        ),
    ]
