# Generated by Django 3.2.16 on 2022-11-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0034_auto_20221127_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityuser',
            name='dp',
            field=models.ImageField(default='default.png', null=True, upload_to='userDP'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='DD4X8C1NZ', max_length=20),
        ),
    ]
