# Generated by Django 3.2.16 on 2023-03-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0035_auto_20221128_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityadminuser',
            name='dp',
            field=models.ImageField(default='default.png', null=True, upload_to='userDP'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='YY8E8I19O', max_length=20),
        ),
    ]
