# Generated by Django 3.2.16 on 2023-10-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0036_auto_20230331_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='BZPD3G0LQ', max_length=20),
        ),
    ]
