# Generated by Django 3.2.16 on 2023-10-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0037_alter_ride_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='322TNN39T', max_length=20),
        ),
    ]
