# Generated by Django 3.2.16 on 2023-12-02 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('REST_API', '0039_alter_ride_groupid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityUser',
            new_name='TankerwalaUser',
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='VQGF18EOV', max_length=20),
        ),
    ]
