# Generated by Django 3.2.16 on 2023-12-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0040_auto_20231203_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='LNY5AC2PM', max_length=20),
        ),
    ]
