# Generated by Django 3.2.16 on 2023-12-03 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0042_alter_ride_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='HN2E6FZ6L', max_length=20),
        ),
        migrations.CreateModel(
            name='waterTankLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField()),
                ('creationDate', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST_API.tankerwalauser')),
            ],
        ),
    ]
