# Generated by Django 3.2.16 on 2023-12-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0043_auto_20231204_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='BBCAX429S', max_length=20),
        ),
    ]
