# Generated by Django 3.2.16 on 2023-12-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0045_alter_ride_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='QUMZWZV6Q', max_length=20),
        ),
    ]
