# Generated by Django 3.2.16 on 2023-12-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0047_alter_ride_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='watertanklevel',
            name='totalCapacity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='A6M88348H', max_length=20),
        ),
    ]
