# Generated by Django 3.2.16 on 2023-12-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0048_auto_20231207_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='U02KMTUE4', max_length=20),
        ),
    ]
