# Generated by Django 3.2.16 on 2023-12-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0049_alter_ride_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankerwalauser',
            name='lastWaterLevelNotification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='groupId',
            field=models.CharField(blank=True, default='SK8KDXPZ4', max_length=20),
        ),
    ]
