
const  STATUS_CODE = {
    CONNECTION_REQ :101,
    IN_COMING_MSG:1901,
    RIDE_NOT_FOUND:111,
    RIDE_ACCEPTED_SUCCESSFULLY:112,
    FOUND_IP_RIDE:191,
    FETCH_OLD_MESSAGES:123,
    CHANGE_ONGOING_RIDE_STATUS : 453,


}

export default STATUS_CODE